project:
  type: website
  output-dir: docs


website:
  title: "Saurav"
  reader-mode: true
  navbar:
    left:
      - text: "About Me"
        href: about.qmd
      - text: "Blogs"
        href: index.qmd
      - text: "TILs"
        href: tils.qmd
      - text: "Notes"
        href: notes/index.qmd

    right:
      - icon: github
        href: https://github.com/saurav2040
      - icon: twitter
        href: https://x.com/Saurav2023
    listing-pages: true

  sidebar:
      - id: notes-sidebar
        style: "floating"
        contents:
          - section: "Notes"
            contents:
              - text: "How to study fastai"
                href: "notes/fastai-guide.qmd"
              - text: "The Cracked MLE Guide"
                href: "notes/mle-guide.qmd"


format:
  html:
    css: custom.css
    theme: flatly
    toc: true
    toc-depth: 3
    toc-title: "On this page"
    toc-location: right
    grid:
          sidebar-width: 250px
          body-width: 800px
          margin-width: 250px   # Reserves distinct space for your TOC
