project:
  type: website
  output-dir: docs
  

website:
  title: "Saurav"
  navbar:
    left:
      - text: "About Me"
        href: about.qmd
      - text: "Blogs"
        href: index.qmd
      - text: "TILs"
        href: tils.qmd

    right:
      - icon: github
        href: https://github.com/saurav2040
      - icon: twitter
        href: https://x.com/Saurav2023
    listing-pages: true
format:
  html:
    css: custom.css
    theme: sandstone  # cerulean, yeti
    toc: true
    toc-depth: 3
    toc-title: Contents
    toc-location: right
    



